# Generated by Django 4.2.27 on 2026-07-20 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Cereal', 'Cereal'), ('Pulse', 'Pulse'), ('Fruit', 'Fruit'), ('Commercial', 'Commercial / Cash Crop')], default='Cereal', max_length=50)),
                ('description', models.TextField()),
                ('ideal_n_range', models.CharField(default='80 - 100 kg/ha', max_length=50)),
                ('ideal_p_range', models.CharField(default='35 - 50 kg/ha', max_length=50)),
                ('ideal_k_range', models.CharField(default='35 - 50 kg/ha', max_length=50)),
                ('ideal_temp_range', models.CharField(default='20°C - 27°C', max_length=50)),
                ('ideal_ph_range', models.CharField(default='6.0 - 7.0', max_length=50)),
                ('water_requirement', models.CharField(default='High (1500 - 2500 mm)', max_length=100)),
                ('harvest_duration', models.CharField(default='120 - 150 days', max_length=100)),
                ('fertilizer_tips', models.TextField(default='Apply Nitrogen in 3 split doses: Basal, Tillering, and Panicle initiation.')),
                ('icon_class', models.CharField(default='fa-seedling', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('FARMER', 'Farmer / User'), ('ADMIN', 'Administrator')], default='FARMER', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, default='Agricultural Zone', max_length=100, null=True)),
                ('farm_size', models.FloatField(default=2.5, help_text='Farm size in acres')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('admin_reply', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RESOLVED', 'Resolved / Responded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CropPredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ph', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('soil_type', models.CharField(default='Alluvial', max_length=50)),
                ('season', models.CharField(default='Kharif', max_length=50)),
                ('predicted_crop', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField(default=95.0)),
                ('top_alternatives', models.TextField(blank=True, default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
